version: 2.1

commands:
  install_and_test:
    description: >-
      Install everything required to run the test suite, then run it.
    steps:
      - run: npm ci

jobs:
  # https://nodejs.org/en/about/releases/
  test_node_lts:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - install_and_test

  test_node_latest:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - install_and_test

  release:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run: npm ci
      - run: npx semantic-release

workflows:
  version: 2
  test_and_release:
    jobs:
      - test_node_lts
      - test_node_latest
      - release:
          filters:
            branches:
              only:
                - master
                - beta
                - alpha
          requires:
            - test_node_lts
            - test_node_latest
